title: Code Notes
description: 
permalink: ':title/'
baseurl: "/blog" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: 

# Author Settings
author: Flávio de Souza
author-img: fdsdev.png # add your photo
about-author: Space for notes and technology studies
social-twitter: flaviosouzadev
social-github: flaviodev # add your Github handle
social-linkedin: flaviodev
social-email: fdsdev@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: 
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 20
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
